name:           Segang Corp.
title:          null
owner:          Segang Corp.
email:          segangcorp@gmail.com

description: 
# blog home에 표시될 blog에 대한 전반적인 설명.

cover: assets/built/images/blog-cover1.png
# blog home에 표시될 blog cover image.

logo:           orca_img.png

favicon: orca_img.png

# navigation: True
# subscribers: True

# Disqus
# disqus: True
# disqus_shortname: xxxxxxxx
# disqus는 온라인 댓글 시스템. 댓글 기능을 사용하기 위해
# disqus를 이용할 것인지 여부와 만약 사용하면
# disqus shortname을 입력 ( disqus username이 아님 )


# Google Analytics
# google_analytics: UA-xxxxxxxx-x # replace with your GA tracking identifier
# Google Analytics을 사용할 경우 GA tracking identifier를 입력
